# Generated by Django 5.0.4 on 2024-05-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0002_ubicacion_alter_entrega_ubicacion'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='orden',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reparto.entrega', verbose_name='Entrega'),
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
