# Generated by Django 5.0.4 on 2024-05-02 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellido_p', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido paterno')),
                ('apellido_m', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido materno')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de documento')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='imagen/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Categoria de productos',
                'verbose_name_plural': 'Categorias de productos',
            },
        ),
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de la entrega',
                'verbose_name_plural': 'Estados de la entrega',
            },
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de la orden',
                'verbose_name_plural': 'Estados de la orden',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto total')),
                ('fechahora_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='imagen/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Residuo',
                'verbose_name_plural': 'Residuos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargos', models.ManyToManyField(to='auth.group')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de entrega')),
                ('detalles_entrega', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Anotaciones del encargado de la entrega')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.empleado', verbose_name='Empleado asignado')),
                ('estado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estadoentrega', verbose_name='Estado de la entrega')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro del orden')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente', verbose_name='Cliente')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.entrega', verbose_name='Entrega')),
                ('estado_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estadoorden', verbose_name='Estado de la orden')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_breve', models.CharField(max_length=100, verbose_name='Descripción breve')),
                ('descripcion_extendida', models.CharField(max_length=500, verbose_name='Descripción extendida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen_principal', models.ImageField(upload_to='imagen/', verbose_name='Imagen principal')),
                ('imagen_secundaria_1', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen secundaria 1')),
                ('imagen_secundaria_2', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen secundaria 2')),
                ('imagen_secundaria_3', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen secundaria 3')),
                ('imagen_360', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen 360')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.orden', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle orden',
                'verbose_name_plural': 'Detalles orden',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto', verbose_name='Producto')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.residuo', verbose_name='Tipo de residuo que puede contener')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=1000, verbose_name='Dirección')),
                ('referencia', models.CharField(max_length=500, verbose_name='Referencia')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código postal')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ubicacion', verbose_name='Ubicación de entrega'),
        ),
    ]
