# Generated by Django 5.0.4 on 2024-05-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='contenedor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='contenedor',
            name='residuo',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='estado_entrega',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='estado_orden',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='pago',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Contenedor',
        ),
        migrations.DeleteModel(
            name='Residuo',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='EstadoEntrega',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.DeleteModel(
            name='EstadoOrden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
