# Generated by Django 5.0.4 on 2024-05-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('ventas', '0001_initial'),
        ('web', '0002_remove_producto_categoria_remove_ciudad_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de entrega')),
                ('detalles_entrega', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Anotaciones del encargado de la entrega')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.empleado', verbose_name='Empleado asignado')),
                ('estado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.estadoentrega', verbose_name='Estado de la entrega')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ubicacion', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
