# Generated by Django 5.0.4 on 2024-05-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('reparto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=1000, verbose_name='Dirección')),
                ('referencia', models.CharField(max_length=500, verbose_name='Referencia')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código postal')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AlterField(
            model_name='entrega',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reparto.ubicacion', verbose_name='Orden'),
        ),
    ]
